#!/bin/bash

# Samuel.ai Server Setup Script
# Run as root or user with sudo

# 1. Update & Basic Tools
sudo apt-get update
sudo apt-get install -y git curl unzip zip nginx supervisor supervisor sqlite3 libcap2-bin software-properties-common

# 2. Add PHP 8.3 Repository
sudo add-apt-repository -y ppa:ondrej/php
sudo apt-get update

# 3. Install PHP 8.3 & Extensions
sudo apt-get install -y php8.3-fpm php8.3-cli php8.3-mongodb php8.3-curl php8.3-mbstring php8.3-xml php8.3-zip php8.3-bcmath php8.3-intl php8.3-readline php8.3-redis php8.3-mysql php8.3-sqlite3

# 4. Install Composer
curl -sS https://getcomposer.org/installer | php
sudo mv composer.phar /usr/local/bin/composer

# 5. Install Node.js & NPM
curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
sudo apt-get install -y nodejs

# 6. Install Redis
sudo apt-get install -y redis-server
sudo systemctl enable redis-server

# 7. Setup Web Directory
sudo mkdir -p /var/www/bibleai
sudo chown -R $USER:$USER /var/www/bibleai
sudo chmod -R 755 /var/www/bibleai

# 8. Setup SSH Key (Add the public key generated by the agent)
mkdir -p ~/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHWtPSif28sqNN+rrnA2cDeTYWuM+yLuGUhEB90nO2xasm2q9RO4BYQFWfU+SmYii0x7SzEMQPP4n8FgpDa2klROXOxUoZqplMuT2ManBganKSBcX9JiuOjJD+aIDhii08VOCrCJwWnPy7oXBjn/bC30I0ehgEcGLleSIM1fCisAT0d+yJ8Zpw/v+BPANKgLOsVMwbOVojYlKb05hJhC6BSJ7kObsuL9ESYey2WAeN1/Pms78YHGoGt0ALsPAuvN4GU5qyiuZ3IM6QlJVhEnPrLK4s/Ve7EfA23+I//+EAxBSmOoOh+vnKgC+8IYl3+ajfKP20+za6tQuMzamSaujYHBkPEnxf6MIZboudamjku7QVPe0drSZrjHnxh30KAnr6RbV3NGZSQ6w+sQ+MlaTO8vYl35sFMj2xYR6NW6Mn/6BWVFgSjq5EwqXoZ/c+NF1v89+GZZ+hLj97mmfDQJW6/0d6O7rMN2yH5DBSTEANgVUWJXa2sFA4mHYxSRjfMJZbrcH4BRqIw8z88Jh2yyISp+i6O4vg974tRucV4kepxm0qkdQL74NqP56IVpO90vxQrEm9fsVQh+QJINmYZ6XOTOxYaHix6Ng1UQyQOEEEeuIBrQWq2IFbbi4DR6j0un/otd0SR/LaRJp61iMS2R6VDt2a8hthoeyaJ01Gnn/Auw== anto@anto" >> ~/.ssh/authorized_keys
chmod 700 ~/.ssh
chmod 600 ~/.ssh/authorized_keys

# 9. Clone Repository (Initial)
if [ ! -d "/var/www/bibleai/.git" ]; then
    git clone https://github.com/AntonyMN/bible-ai-samuel.git /var/www/bibleai
fi

# 10. Install MongoDB (Atlas is recommended but we can install local for staging)
sudo apt-get install -y gnupg wget
wget -qO - https://www.mongodb.org/static/pgp/server-7.0.asc | sudo gpg --dearmor | sudo tee /usr/share/keyrings/mongodb-server-7.0.gpg > /dev/null
echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list
sudo apt-get update
sudo apt-get install -y mongodb-org
sudo systemctl start mongod
sudo systemctl enable mongod

echo "Server Setup Phase 1 Complete. Please configure NGINX next."
